swagger: '2.0'
info:
  description: API for the managing flight logs
  version: 1.0.0
  title: Flight Log API
  contact:
    email: keith@savvycreationsdesign.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api/logs:
    post:
      summary: Add Log Records
      description: Add a list of log records
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: records
        description: Records to add
        schema:
          $ref: '#/definitions/Records'
      responses:
        204:
          description: Records successufully added
        400:
          description: Invalid records
  /api/generations:
    get:
      summary: Get Generations
      description: Get the list available generations
      produces:
      - application/json
      responses:
        200:
          description: Records successufully added
          schema:
            type: array
            items:
              type: integer
  /api/find/generation:
    get:
      summary: Find Generation Records
      description: Find the records for a drone generation
      produces:
      - application/json
      parameters:
      - in: query
        name: generation
        required: true
        type: integer
      responses:
        200:
          description: Records successufully found
          schema:
            $ref: '#/definitions/Records'
  /api/find/dates:
    get:
      summary: Find Date Range
      description: Find the records in a date range
      produces:
      - application/json
      parameters:
      - in: query
        name: startDate
        type: string
        format: date-time
      - in: query
        name: endDate
        type: string
        format: date-time
      responses:
        200:
          description: Records successufully found
          schema:
            $ref: '#/definitions/Records'
  /api/find/duration:
    get:
      summary: Find Duration Records
      description: Find the records for flights within a given duration
      produces:
      - application/json
      parameters:
      - in: query
        name: duration
        required: true
        type: integer
      responses:
        200:
          description: Records successufully found
          schema:
            $ref: '#/definitions/Records'
  /api/find/area:
    get:
      summary: Find Area Records
      description: Find the records for flights within a give geo area
      produces:
      - application/json
      parameters:
      - in: query
        name: left
        required: true
        type: number
        minimum: -180
        maximum: 180
      - in: query
        name: right
        required: true
        type: number
        minimum: -180
        maximum: 180
      - in: query
        name: top
        required: true
        type: number
        minimum: -90
        maximum: 90
      - in: query
        name: bottom
        required: true
        type: number
        minimum: -90
        maximum: 90
      responses:
        200:
          description: Records successufully found
          schema:
            $ref: '#/definitions/Records'
definitions:
  Records:
    type: 'array'
    items:
      type: object
      required:
      - drone
      - generation
      - startDate
      - endDate
      - location
      - imagePath
      properties:
        drone:
          type: integer
          example: 1021
        generation:
          type: integer
          example: 10
        startDate:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        endDate:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        location:
          type: array
          items:
            type: number
            minimum: -180
            maximum: 180
          minItems: 2
          maxItems: 2
          example: [30.02, 40.789]
        imagePath:
          type: string
          format: uri
          example: https://s3.amazonaws.com/bucket/path/image.png
